### ISSUE TITLE
Deletion from Vector DB

### ISSUE THREAD

**Issue by iamfrankiemoran** [athrael-soju/titanium-lite-1.3#5]
When deleting files, it isn't deleting the correct files from the vector db. 

For instance, I uploaded two files, processed them after uploading each file. Then deleted the last file to be uploaded and processed, however, it deleted everything in the vector db whereas it should have deleted that one file in the vector db. 

Investigate and resolve

**Comment by athrael-soju** [comment]
Resolved by https://github.com/athrael-soju/titanium-lite-1.3/pull/7
