### ISSUE TITLE
Processed File Status

### ISSUE THREAD

**Issue by iamfrankiemoran** [athrael-soju/titanium-lite-1.3#6]
If you upload a couple of files, after some time the application loses context of what files have been processed or not. 

Example, in the recording of 1.3 demo you'll noticed that two files are uploaded but only my CV is processed. However, the Vector DB had the Washing Machine Manual processed so its like it has lost the status of it

**Comment by athrael-soju** [comment]
Resolved by https://github.com/athrael-soju/titanium-lite-1.3/pull/7
